import Chat from "../../model/chat.model.js"

const createMessageService = async ({ text, sender, chatData }) => {
  if (!text || !sender || !chatData) return false

  // receiver ID (string)
  const receiverId = chatData.participants.find(p => p._id !== sender)?._id
  
  if (!receiverId) return false

  try {
    const chat = await Chat.findOne({
      participants: { $all: [sender, receiverId] }
    })

    if (!chat) return false

    const newMessage = {
      sender,
      content: text,
      sentAt: new Date() // This matches your schema field name
    }

    chat.messages.push(newMessage)
    await chat.save()

    // Return the full message with _id generated by MongoDB
    const savedMessage = chat.messages[chat.messages.length - 1]
    
    return {
      _id: savedMessage._id.toString(),
      sender: savedMessage.sender.toString(),
      content: savedMessage.content,
      sentAt: savedMessage.sentAt.toISOString(),
      edited: savedMessage.edited,
      isRead: savedMessage.isRead
    }
  } catch (err) {
    return false
  }
}

export default createMessageService